version: '3'
services:
  app1:
    build: ./app1
    ports:
    - "5001:5000"
  app2:
    build: ./app2
    ports:
    - "5002:5000"
  nginx:
    build: ./nginx
    ports:
    - "8080:80"
    depends_on:
    - app1
    - app2
  mysql:
    container_name: mysql
    image: percona:8-centos
    volumes:
      - ./docker/mysql/setup:/docker-entrypoint-initdb.d
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/conf:/etc/mysql/conf.d:ro
    environment:
      - MYSQL_ROOT_PASSWORD=<mypassword>
      - MYSQL_DATABASE=<database>
      - MYSQL_USER=<username>
      - MYSQL_PASSWORD=<password>
    stop_grace_period: 30s 
    restart: always
